language: node_js
node_js:
- "node"
cache: npm
install:
  - npm install -g now
script: npm run deploy
after_script: npm run alias
env:
  global:
    secure: jROGbVM1inUhaef5elGaWmwl2dkL5i/TdGw8qM/JEkG9Vrb5qLw6oN5+C4WMYQx4W6r5YkXbixG8feqYR9JV2QtWn4WausS6CqWvumQCH15a15gJC/SOEcH9UkVwmFfeWhY34bFC/7VzRT/p2rU7AjVT2digwp6Oc3VLkDYWE3l1VofG0TFxQ8IItjCVmuqxgWC3VnmkF44RNESAlPJyHKrK49pXjlykUc+5plcfhvo92fz38Q8DpRtFVuuhtcJMOAB9jVmC9hPvRLWiDyJZR3Kb24mnF5vsT3t8Jaf+DfZcwbbKNVfQgfHhiN60iEal+giRtM7n1l6I8XhJSgCdDs0FJ9E0u2hDnoAoYxXHCfcs6SV75Zrx6JNfNcLFLd3oRv8wl/UcJiBIDXJ7lPOBF+wWeOfVul/jLFa9+BQsrPEI6T6gplbVooKvhQcbV+ZdSHWRsRflwFIgTrXCwkIsf7hQ+ExmlKW1cBJfQjywlMtU2L76PtavjpmlhcVP2YkRP0xMkH5yz/wIZ4kBPzSGldURJzZdNJ0JJtmdV342qGSGfbgKN4W75V9qL4V0x6zA1rSRdxBcD5ltwv4vZlEItENxKZZkti1C49j683TLLKceXN4wafVggv1xIgmge5uskEkh6Q6la5mKeq1TSoomX2uxmKnio3n4aBuifnZ5UxQ=
