language: node_js
node_js:
- node
cache: npm
install:
- npm install -g now
script: 
- printf "LASTMOD=%s\n" $(date -u +%Y-%m-%dT%H:%M:%SZ) > .env
- printf "COMMIT=%s\n" $(git rev-parse --short HEAD) > .env
- now --public --dotenv -e NODE_ENV=production -e GA_ID=$GA_ID --token $NOW_TOKEN
after_script: 
- npm run alias
env:
  global:
  - secure: jROGbVM1inUhaef5elGaWmwl2dkL5i/TdGw8qM/JEkG9Vrb5qLw6oN5+C4WMYQx4W6r5YkXbixG8feqYR9JV2QtWn4WausS6CqWvumQCH15a15gJC/SOEcH9UkVwmFfeWhY34bFC/7VzRT/p2rU7AjVT2digwp6Oc3VLkDYWE3l1VofG0TFxQ8IItjCVmuqxgWC3VnmkF44RNESAlPJyHKrK49pXjlykUc+5plcfhvo92fz38Q8DpRtFVuuhtcJMOAB9jVmC9hPvRLWiDyJZR3Kb24mnF5vsT3t8Jaf+DfZcwbbKNVfQgfHhiN60iEal+giRtM7n1l6I8XhJSgCdDs0FJ9E0u2hDnoAoYxXHCfcs6SV75Zrx6JNfNcLFLd3oRv8wl/UcJiBIDXJ7lPOBF+wWeOfVul/jLFa9+BQsrPEI6T6gplbVooKvhQcbV+ZdSHWRsRflwFIgTrXCwkIsf7hQ+ExmlKW1cBJfQjywlMtU2L76PtavjpmlhcVP2YkRP0xMkH5yz/wIZ4kBPzSGldURJzZdNJ0JJtmdV342qGSGfbgKN4W75V9qL4V0x6zA1rSRdxBcD5ltwv4vZlEItENxKZZkti1C49j683TLLKceXN4wafVggv1xIgmge5uskEkh6Q6la5mKeq1TSoomX2uxmKnio3n4aBuifnZ5UxQ=
  - secure: ZYwmaxGm7Sk3htAiBnbRxsA9xhw53DQea1thn/So7LY5vmLS4JeBYdaZCgWgtddRCc1yc5Knz9MaaAampQdU0GIyp7u6ctMBnmFVBi6Jo1xbYjGO67movp2tsRH4ePxA2uq2+wtnM/6i9jS4zoaejwhaUv8nkYuYEvWZOJYJzdNXEw9WpjvtRLXIgv/bNp/tdVsHX0O6JyTMd98UxgjlXYfgNlL6rVETGVFp//dJuoZAaVn2Ri3LY8gYClcHXqqCxj53jR2ERBJh7/3r7eW5NCh5jk6GOiq6Ok+ka4dX2xBH7TVU7G3u5p3EnhRS0cfzaZT6srRi80J/395IwppI83x2PDyL6TVa5AaqS1lU/XW17/SWJzxRs8U4GcCWDTGeyD+oVKSQZRWQVjoVe0zkjVJf3/09jw0Ei2U78W79GIbEeC7UZR+deKrlhkV8L+U/myyN+5hiseZ/NcP+3miPSct5RDdZwCrLKpXsjLW+BEpyu/iEJcOhgF4K3oo++o1Ol9ryY5wkI5+2iHYt2ULC8d3jOQPGSugWK2H9YAusNGM72xhIZWIQYdrOEmjfZi/FdxFmaCDXlwWRzgv2jB4BQlNkXeRCPetfEpKrVAW3kVEHrVM9vhS2vMTD4ochXUeApR8A1RbabTNpeR+bVPpSbVInsbWXoIu77iwhZGxu9S4=
