{
  "automatic_scaling": {
    "max_instances": 1,
    "min_instances": 1
  },
  "env_variables": {
    "GA_ID": "UA-328425-45"
  },
  "handlers": [
    {
      "redirect_http_response_code": 301,
      "script": "auto",
      "secure": "always",
      "url": "/.*"
    }
  ],
  "runtime": "nodejs12"
}
