#
# _config.yml for Google Cloud Icons
#

exclude: [ "CNAME", "**/*_src*" ]
permalink: /blog/:year/:month/:day/:title/index.:output_ext
production_url: https://cdn.simpleshare.dev
title: SimpleShare Icons
markdown: kramdown
plugins:
  - jekyll-redirect-from
redirect_from:
  json: false
theme: null
links:
  - name: "Return to SimpleShare.dev"
    url: "https://simpleshare.dev/"
  - name: "Source"
    url: "https://github.com/fileformat/simpleshare/tree/main/docs/tile"
  - name: "More logos"
    url: "https://www.vectorlogo.zone/"
  - name: "Logo Search"
    url: "https://logosear.ch/"
  - name: "Icon Search"
    url: "https://iconsear.ch/"