name: build

on:
  push:
    branches:
    - master

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node 12 (req'd for AppEngine Free)
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install

      - run: yarn run build

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Configure gcloud CLI
      - name: gcloud Set up
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Install yq
        run: sudo snap install yq

      - name: Set COMMIT 
        run: |
          yq write --inplace ./app.yaml env_variables.COMMIT ${GITHUB_SHA:0:7}

      - name: Set LASTMODIFIED
        run: |
          yq write --inplace ./app.yaml env_variables.LASTMOD "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

      - name: Deploy to AppEngine
        run: |
          gcloud app deploy --quiet
